### ISSUE TITLE
Rename to Zeebe

### ISSUE THREAD

**Issue by meyerdan** [zeebe-io/tasks#29]
Let's collect things that need to be renamed

~~Github orga~~ (postponed see camunda-tngp/zeebe/issues/321)
- [x] Github repos (=> broken down)
- [x] java packages and classes (=> broken down)
- [x] maven artifacts (=> seperate issue #30)
- [x] ci artifacts
- [x] nexus repositories
- [x] downgrade versions to 0.1.0-SNAPSHOT
- [x] mailing list
- [ ] what is up? session calendar invite

**Comment by berndruecker** [comment]
What's the reasoning behind zbc in "zbc-go" - ZeeBe-Client? At least this should read zeebe-client-go as it is something important for the users and not internal - no?

**Comment by menski** [comment]
I think c stands for client. @jsam any opinions on this?
