### ISSUE TITLE
Execute SpotBugs in Maven build

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/tasks#32]
* Run [SpotBugs](https://spotbugs.github.io/) with every Maven build
* Configure it such that only patterns are detected which ALWAYS result in unintended behavior (for example: `#equals` invocation on objects of different type)
* If anything is detected, let the build fail
* Do this for all projects

**Comment by menski** [comment]
moved to https://github.com/zeebe-io/zeebe/issues/515
