### ISSUE TITLE
Use overflow after hash table max size is reached

### ISSUE THREAD

**Issue by Zelldon** [zeebe-io/tasks#38]
Should use overflow on split if the maximum hash table size is reached and the hash table can't be increased anymore.

**Comment by Zelldon** [comment]
Commit https://github.com/zeebe-io/zb-util/commit/11d9e40ebe2b15fa2b355931571122f2d4c2b6d4

**Comment by menski** [comment]
@saig0 is this ticket done? You moved it in the column but its not closed?

**Comment by Zelldon** [comment]
This project tooling is terrible ...

**Comment by menski** [comment]
@Zelldon we will find a solution :icecream:
